### ISSUE TITLE
Viewport meta test fails with some combinations of content attribute

### ISSUE THREAD

**Issue by joestrong** [freshleafmedia/api.scrutinizer#4]
This meta tag does not pass:
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`

The test currently doesn't like the inclusion of minimum-scale, maximum-scale or user-scalable.

I believe "width=device-width" to be the bare minimum to stop zoomed-out-desktop-view
If "initial-scale" is required too, that is fine, but the order of these shouldn't matter, and the inclusion of other properties, i.e. minimum-scale, maximum-scale, or user-scalable shouldn't make the test fail

**Comment by moebrowne** [comment]
This is has now been changed so that only the `width=device-width` property is required
